INSERT INTO estaciones (nombre) VALUES
("Acevedo"),
("Aguacatala"),
("Alejandro Echavarr¡a"),
("Alpujarra"),
("Andalucía"),
("Arvi"),
("Ayura"),
("Barrio Córdoba"),
("Barrio Calasanz"),
("Barrio Colón"),
("Barrio Colombia"),
("Barrio Los Colores"),
("Barrio Pilarica"),
("Bello"),
("Berín"),
("Bicentenario"),
("Buenos Aires"),
("Caribe"),
("Catedral"),
("Chagualo"),
("Cisneros"),
("Ciudadela Universitaria"),
("Doce de Octubre"),
("El Pinal"),
("El Progreso"),
("Envigado"),
("Estadio"),
("Exposiciones"),
("Fátima"),
("Facultad de Minas"),
("Floresta"),
("Gardel"),
("Hospital"),
("Industriales"),
("Itagui"),
("Juan XXIII"),
("La Aurora"),
("La Estrella"),
("La Palma"),
("La Playa"),
("Las Esmeraldas"),
("Las Torres"),
("Laureles"),
("Los Alpes"),
("Los Pinos"),
("Loyola"),
("Madera"),
("Manrique"),
("Minorista"),
("Miraflores"),
("Niquia"),
("Nutibara"),
("Oriente"),
("Pabellón del Agua EPM"),
("Palos Verdes"),
("Parque Berrío"),
("Parque de Aranjuez"),
("Parque de Belen"),
("Perpetuo Socorro"),
("Plaza Mayor"),
("Poblado"),
("Popular"),
("Prado"),
("Rosales"),
("Ruta N - U de A"),
("Sabaneta"),
("San Antonio"),
("San Javier"),
("San José"),
("Santa Gema"),
("Santa Lucia"),
("Santo Domingo"),
("SENA"),
("Suramericana"),
("Trece de Noviembre"),
("Tricentenario"),
("Universal"),
("Universidad"),
("Universidad de Medellín"),
("Vallejuelos"),
("Villa de Aburrá"),
("Villa Sierra");