insert into trenes (line_id, tipo, año) values (9, 'Avenger', 1998);
insert into trenes (line_id, tipo, año) values (6, 'SJ', 1995);
insert into trenes (line_id, tipo, año) values (1, 'GTI', 2005);
insert into trenes (line_id, tipo, año) values (5, 'Mini', 1963);
insert into trenes (line_id, tipo, año) values (11, 'LR3', 2008);
insert into trenes (line_id, tipo, año) values (8, 'Neon', 1999);
insert into trenes (line_id, tipo, año) values (9, 'Sierra 1500', 2007);
insert into trenes (line_id, tipo, año) values (4, 'Colorado', 2004);
insert into trenes (line_id, tipo, año) values (1, 'DeVille', 2004);
insert into trenes (line_id, tipo, año) values (5, 'X-90', 1998);
insert into trenes (line_id, tipo, año) values (11, 'Electra', 1986);
insert into trenes (line_id, tipo, año) values (8, 'Focus', 2006);
insert into trenes (line_id, tipo, año) values (6, 'Neon', 2001);
insert into trenes (line_id, tipo, año) values (1, 'Frontier', 2011);
insert into trenes (line_id, tipo, año) values (9, '3500', 2000);
insert into trenes (line_id, tipo, año) values (5, 'LeSabre', 1985);
insert into trenes (line_id, tipo, año) values (11, 'Accent', 2013);
insert into trenes (line_id, tipo, año) values (7, 'XLR', 2009);
insert into trenes (line_id, tipo, año) values (3, 'Silverado 2500', 2009);
insert into trenes (line_id, tipo, año) values (3, '1 Series', 2009);
insert into trenes (line_id, tipo, año) values (6, 'Sierra 1500', 2000);
insert into trenes (line_id, tipo, año) values (5, 'GS', 1999);
insert into trenes (line_id, tipo, año) values (3, 'Sentra', 1991);
insert into trenes (line_id, tipo, año) values (2, 'Miata MX-5', 2004);
insert into trenes (line_id, tipo, año) values (9, 'LeSabre', 2004);
insert into trenes (line_id, tipo, año) values (8, '9-3', 2012);
insert into trenes (line_id, tipo, año) values (9, 'Prizm', 1993);
insert into trenes (line_id, tipo, año) values (12, 'Durango', 2007);
insert into trenes (line_id, tipo, año) values (10, 'Escalade EXT', 2008);
insert into trenes (line_id, tipo, año) values (7, 'Durango', 2001);
insert into trenes (line_id, tipo, año) values (11, 'Firebird', 1968);
insert into trenes (line_id, tipo, año) values (3, 'Volare', 1976);
insert into trenes (line_id, tipo, año) values (10, 'Fox', 1993);
insert into trenes (line_id, tipo, año) values (9, 'Rondo', 2010);
insert into trenes (line_id, tipo, año) values (5, 'Virage', 2011);
insert into trenes (line_id, tipo, año) values (3, 'Continental', 1990);
insert into trenes (line_id, tipo, año) values (8, 'Daewoo Lacetti', 2005);
insert into trenes (line_id, tipo, año) values (3, 'A6', 1999);
insert into trenes (line_id, tipo, año) values (6, '1500', 1995);
insert into trenes (line_id, tipo, año) values (2, 'Eurovan', 1994);
insert into trenes (line_id, tipo, año) values (2, 'G25', 2011);
insert into trenes (line_id, tipo, año) values (1, '3500 Club Coupe', 1995);
insert into trenes (line_id, tipo, año) values (8, 'Range Rover', 2000);
insert into trenes (line_id, tipo, año) values (9, 'S8', 2002);
insert into trenes (line_id, tipo, año) values (2, 'Range Rover', 2011);
insert into trenes (line_id, tipo, año) values (4, 'Gran Sport', 2006);
insert into trenes (line_id, tipo, año) values (6, 'Grand Vitara', 2011);
insert into trenes (line_id, tipo, año) values (3, 'Protege', 1995);
insert into trenes (line_id, tipo, año) values (8, 'Savana 2500', 2000);
insert into trenes (line_id, tipo, año) values (2, 'Highlander', 2012);
insert into trenes (line_id, tipo, año) values (7, 'Land Cruiser', 1993);
insert into trenes (line_id, tipo, año) values (4, 'Sierra 3500', 2002);
insert into trenes (line_id, tipo, año) values (6, 'Hombre Space', 2000);
insert into trenes (line_id, tipo, año) values (1, 'G35', 2006);
insert into trenes (line_id, tipo, año) values (4, 'Grand Caravan', 2003);
insert into trenes (line_id, tipo, año) values (4, 'S-Class', 2010);
insert into trenes (line_id, tipo, año) values (4, 'Passat', 2009);
insert into trenes (line_id, tipo, año) values (10, 'Park Avenue', 1992);
insert into trenes (line_id, tipo, año) values (12, 'GS', 2008);
insert into trenes (line_id, tipo, año) values (4, 'QX56', 2007);
insert into trenes (line_id, tipo, año) values (6, 'Escort', 1992);
insert into trenes (line_id, tipo, año) values (4, 'Freestar', 2005);
insert into trenes (line_id, tipo, año) values (12, 'Ion', 2004);
insert into trenes (line_id, tipo, año) values (9, 'Firebird', 2000);
insert into trenes (line_id, tipo, año) values (2, 'Sonoma', 1995);
insert into trenes (line_id, tipo, año) values (1, 'TL', 2007);
insert into trenes (line_id, tipo, año) values (5, 'Cherokee', 1999);
insert into trenes (line_id, tipo, año) values (6, '745', 2002);
insert into trenes (line_id, tipo, año) values (7, '9-5', 2011);
insert into trenes (line_id, tipo, año) values (6, 'QX', 2012);
insert into trenes (line_id, tipo, año) values (9, 'MPV', 1993);
insert into trenes (line_id, tipo, año) values (5, 'Accord', 2004);
insert into trenes (line_id, tipo, año) values (1, 'XF', 2009);
insert into trenes (line_id, tipo, año) values (2, 'MX-6', 1991);
insert into trenes (line_id, tipo, año) values (10, 'DeVille', 2002);
insert into trenes (line_id, tipo, año) values (3, 'C8', 2005);
insert into trenes (line_id, tipo, año) values (9, 'B2500', 2001);
insert into trenes (line_id, tipo, año) values (4, 'RX', 2006);
insert into trenes (line_id, tipo, año) values (12, 'HS', 2012);
insert into trenes (line_id, tipo, año) values (1, 'Explorer', 2004);
insert into trenes (line_id, tipo, año) values (1, 'M-Class', 2012);
insert into trenes (line_id, tipo, año) values (2, 'NSX', 1994);
insert into trenes (line_id, tipo, año) values (8, 'CLK-Class', 2007);
insert into trenes (line_id, tipo, año) values (4, 'Caravan', 2003);
insert into trenes (line_id, tipo, año) values (6, 'Charger', 1970);
insert into trenes (line_id, tipo, año) values (1, 'A4', 2009);
insert into trenes (line_id, tipo, año) values (3, 'Mazda6', 2005);
insert into trenes (line_id, tipo, año) values (4, 'Tiburon', 2003);
insert into trenes (line_id, tipo, año) values (10, 'Voyager', 1996);
insert into trenes (line_id, tipo, año) values (12, 'CX-9', 2011);
insert into trenes (line_id, tipo, año) values (3, 'Sierra 3500', 2005);
insert into trenes (line_id, tipo, año) values (9, 'Impala', 2002);
insert into trenes (line_id, tipo, año) values (11, 'SLK-Class', 2000);
insert into trenes (line_id, tipo, año) values (11, 'Z4 M', 2006);
insert into trenes (line_id, tipo, año) values (10, 'Discovery', 2011);
insert into trenes (line_id, tipo, año) values (12, 'Cayenne', 2003);
insert into trenes (line_id, tipo, año) values (7, 'Grand Prix', 1980);
insert into trenes (line_id, tipo, año) values (12, 'Montero', 1994);
insert into trenes (line_id, tipo, año) values (6, 'Suburban 1500', 1998);
insert into trenes (line_id, tipo, año) values (1, 'Intrepid', 1998);
