insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Giulio Dulling', '44 Cottonwood Road', '1991/02/26');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Ashlee Annets', '08 Clyde Gallagher Center', '1991/06/07');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Maris Stirton', '05468 Dahle Street', '1962/07/12');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Cleve Franchyonok', '567 Ridgeview Alley', '1974/04/17');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Goddard Zylberdik', '06 East Junction', '1975/12/13');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Coleman Joiner', '48 Morrow Street', '1996/02/17');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Rodney Duffy', '56525 Gateway Plaza', '2007/07/01');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Romy Bonfield', '15 Express Avenue', '1950/01/02');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Kaleena Stanlick', '38673 Prairie Rose Alley', '1975/09/17');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Iver Mahoney', '2 Gale Court', '2000/08/12');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Nico Madle', '51566 Ludington Terrace', '1978/04/19');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Jasmin Zamboniari', '9915 Mcbride Junction', '1993/07/29');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Brooke Fussell', '8756 Green Crossing', '1988/04/24');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Ina Robbert', '0 Hollow Ridge Plaza', '1954/08/20');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Angelico Hotchkin', '2641 Amoth Plaza', '1981/09/01');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Brit Ferrers', '7050 Redwing Crossing', '1992/11/12');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Ephrayim Crop', '905 Kings Point', '1973/05/17');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Edi Kegley', '52 Troy Park', '1951/02/11');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Papagena Gerssam', '26866 Cherokee Court', '1968/10/29');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Berrie Halsworth', '1 Hintze Alley', '1999/05/30');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Marti Ganny', '66 Morrow Junction', '1994/03/03');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Fallon Valeri', '2906 Superior Avenue', '1963/04/09');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Jana Guinane', '9 Derek Circle', '1998/07/06');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Hamish Tytterton', '70 Thierer Park', '1961/02/02');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Tommie Freckingham', '4322 1st Point', '1979/04/27');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Helen Lax', '76517 Crowley Point', '1973/08/17');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Reine Marchand', '03 Portage Pass', '1985/08/16');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Jeannine Trustrie', '2 Pawling Parkway', '1950/05/25');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Rochella Ambresin', '10 West Drive', '1983/10/18');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Marci Durno', '9 Bluejay Crossing', '1985/07/04');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Domeniga Witts', '607 Atwood Center', '1959/01/04');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Evvy Alp', '56242 Donald Junction', '1997/11/29');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Gilberto Dibdin', '91170 Red Cloud Parkway', '2008/10/20');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Michell Kersting', '58 Mandrake Trail', '1993/06/02');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Sarina Enderwick', '630 Welch Alley', '1975/06/26');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Hillier Tythe', '6152 5th Place', '2007/01/03');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Esme Ronca', '22 Bultman Point', '1991/12/09');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Alfred Griston', '704 Scofield Parkway', '2003/08/11');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Roanna Proudlove', '03 Shopko Hill', '1984/12/20');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Maressa Whithorn', '6 Jana Point', '1973/02/01');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Fawnia Bradtke', '3 Talisman Center', '1962/04/12');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Abbey Wrettum', '9 Crownhardt Plaza', '1983/08/29');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Aundrea Burdus', '1 Acker Parkway', '1962/10/29');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Lion Currin', '6648 Fordem Center', '1971/10/13');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Elbertine Brizland', '876 Farragut Center', '1962/12/04');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Nana Emnoney', '552 Meadow Ridge Terrace', '1987/03/17');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Demetri Pigney', '36 Hoffman Drive', '2003/09/06');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Keefe O''Dunniom', '87961 Melrose Pass', '1977/08/17');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Marylinda Fallis', '44 Springview Alley', '2006/01/02');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Davon Bettam', '6 Hoard Place', '2006/10/09');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Nolly Christoffersen', '9608 Waubesa Place', '1957/02/12');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Kelsey Egerton', '55 Maple Terrace', '1980/05/15');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Carmela Simioni', '3432 Sheridan Way', '1975/03/12');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Florian Kiwitz', '8 Derek Court', '2007/02/01');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Auberta Kenset', '80397 Spohn Crossing', '1950/01/24');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Robbyn Stainland', '82914 Boyd Park', '1956/04/18');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Margalo Geffcock', '3345 Algoma Lane', '1966/09/09');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Tuck Blunkett', '8 Garrison Plaza', '1964/07/09');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Ophelie Cortez', '43 Hauk Terrace', '1961/03/09');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Merrel Stone', '1642 Acker Center', '1998/05/28');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Margot Izakoff', '2 Boyd Plaza', '1971/10/25');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Perle Fogt', '74427 Sachtjen Park', '1995/04/12');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Callie Cready', '5245 Delaware Parkway', '1998/03/04');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Philbert Aitken', '7535 Sachs Way', '1950/03/13');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Davina Marzele', '6188 Brentwood Trail', '1958/05/25');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Simone Hargate', '97717 Sherman Place', '1963/08/07');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Hedvige Toplin', '9 Garrison Terrace', '2006/12/19');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Derril Castan', '09 Bultman Circle', '1978/03/09');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Gualterio Kalaher', '30593 Mallard Trail', '1961/05/23');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Virginia Rubenfeld', '45643 Butternut Parkway', '1982/02/28');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Shaughn Benn', '8 Pepper Wood Crossing', '1983/06/13');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Thurstan Goggen', '5174 Hollow Ridge Lane', '1958/05/31');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Fionna Coarser', '525 Transport Way', '1994/07/09');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Florian Jost', '954 Mosinee Place', '1959/11/14');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Jennette Abramovici', '509 Goodland Junction', '1979/01/31');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Dot Beechcraft', '204 Hovde Center', '1975/06/05');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Maye Whiles', '6 Hanson Trail', '1952/12/01');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Shannen Wrinch', '85 Burrows Junction', '1969/01/12');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Carmon Pilch', '79452 Kingsford Avenue', '1992/06/29');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Janene Vernall', '7 Parkside Road', '1978/05/12');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Jakie Dell''Abbate', '019 Lakewood Gardens Road', '1981/04/13');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Joe Andreou', '1 Colorado Terrace', '2002/02/01');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Merla Finden', '8699 Grover Avenue', '1985/01/21');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Lew Stobbe', '0 Linden Center', '1984/08/13');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Cacilia McCaskill', '3990 Morrow Parkway', '1953/02/26');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Farra Carson', '603 Onsgard Terrace', '2008/09/15');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Bamby Chudleigh', '5 Colorado Terrace', '2000/03/16');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Jacquelynn Crooke', '98 Golden Leaf Place', '1964/11/03');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Nicola Staziker', '1 Jenna Trail', '2008/05/17');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Berkie Hayen', '96626 Hermina Terrace', '1985/12/28');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Lauren Agglio', '74832 Schlimgen Way', '1998/07/12');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Elaine Mumm', '23 Hermina Road', '1950/08/26');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Emmalyn Napoleone', '3 Fisk Pass', '1978/06/09');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Halimeda Pavelin', '9 Aberg Pass', '1997/02/17');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Brianne Doerren', '65 Sage Hill', '1981/06/30');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Arlan Semper', '91481 Autumn Leaf Way', '1981/06/06');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Marigold Sorbey', '4048 Mcbride Parkway', '2000/03/11');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Conny Bunny', '49 Gale Park', '1965/05/20');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Colet Russ', '22449 Dwight Court', '2000/06/23');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Almire Hagwood', '0044 Laurel Avenue', '1982/06/14');
