insert into trenes (modelo, capacidad) values ('Murciélago LP640', 1);
insert into trenes (modelo, capacidad) values ('3500', 2);
insert into trenes (modelo, capacidad) values ('New Beetle', 3);
insert into trenes (modelo, capacidad) values ('Prius', 4);
insert into trenes (modelo, capacidad) values ('Regal', 5);
insert into trenes (modelo, capacidad) values ('Concorde', 6);
insert into trenes (modelo, capacidad) values ('A6', 7);
insert into trenes (modelo, capacidad) values ('PT Cruiser', 8);
insert into trenes (modelo, capacidad) values ('Sportage', 9);
insert into trenes (modelo, capacidad) values ('Camry', 10);
insert into trenes (modelo, capacidad) values ('Impreza', 11);
insert into trenes (modelo, capacidad) values ('MKX', 12);
insert into trenes (modelo, capacidad) values ('CR-V', 13);
insert into trenes (modelo, capacidad) values ('Mirage', 14);
insert into trenes (modelo, capacidad) values ('CTS', 15);
insert into trenes (modelo, capacidad) values ('Elantra', 16);
insert into trenes (modelo, capacidad) values ('Range Rover', 17);
insert into trenes (modelo, capacidad) values ('Trans Sport', 18);
insert into trenes (modelo, capacidad) values ('A8', 19);
insert into trenes (modelo, capacidad) values ('Mustang', 20);
insert into trenes (modelo, capacidad) values ('RS4', 21);
insert into trenes (modelo, capacidad) values ('F150', 22);
insert into trenes (modelo, capacidad) values ('Celica', 23);
insert into trenes (modelo, capacidad) values ('H3T', 24);
insert into trenes (modelo, capacidad) values ('Leone', 25);
insert into trenes (modelo, capacidad) values ('SLK-Class', 26);
insert into trenes (modelo, capacidad) values ('Ram 2500', 27);
insert into trenes (modelo, capacidad) values ('ES', 28);
insert into trenes (modelo, capacidad) values ('Fairlane', 29);
insert into trenes (modelo, capacidad) values ('57S', 30);
insert into trenes (modelo, capacidad) values ('Precis', 31);
insert into trenes (modelo, capacidad) values ('GS', 32);
insert into trenes (modelo, capacidad) values ('SL-Class', 33);
insert into trenes (modelo, capacidad) values ('Roadmaster', 34);
insert into trenes (modelo, capacidad) values ('Ram Van B350', 35);
insert into trenes (modelo, capacidad) values ('XC70', 36);
insert into trenes (modelo, capacidad) values ('CR-V', 37);
insert into trenes (modelo, capacidad) values ('Tiguan', 38);
insert into trenes (modelo, capacidad) values ('Suburban 2500', 39);
insert into trenes (modelo, capacidad) values ('PT Cruiser', 40);
insert into trenes (modelo, capacidad) values ('Spectra5', 41);
insert into trenes (modelo, capacidad) values ('Grand Cherokee', 42);
insert into trenes (modelo, capacidad) values ('SVX', 43);
insert into trenes (modelo, capacidad) values ('Ram 3500', 44);
insert into trenes (modelo, capacidad) values ('Suburban 2500', 45);
insert into trenes (modelo, capacidad) values ('G-Series 2500', 46);
insert into trenes (modelo, capacidad) values ('Lancer', 47);
insert into trenes (modelo, capacidad) values ('S8', 48);
insert into trenes (modelo, capacidad) values ('Seville', 49);
insert into trenes (modelo, capacidad) values ('V8', 50);
insert into trenes (modelo, capacidad) values ('Silverado 3500', 51);
insert into trenes (modelo, capacidad) values ('626', 52);
insert into trenes (modelo, capacidad) values ('Pajero', 53);
insert into trenes (modelo, capacidad) values ('Ram 2500', 54);
insert into trenes (modelo, capacidad) values ('Firebird Formula', 55);
insert into trenes (modelo, capacidad) values ('Highlander', 56);
insert into trenes (modelo, capacidad) values ('Mazda6', 57);
insert into trenes (modelo, capacidad) values ('Grand Prix', 58);
insert into trenes (modelo, capacidad) values ('H2', 59);
insert into trenes (modelo, capacidad) values ('Cavalier', 60);
insert into trenes (modelo, capacidad) values ('Taurus', 61);
insert into trenes (modelo, capacidad) values ('S60', 62);
insert into trenes (modelo, capacidad) values ('Dakota', 63);
insert into trenes (modelo, capacidad) values ('Eclipse', 64);
insert into trenes (modelo, capacidad) values ('Expedition', 65);
insert into trenes (modelo, capacidad) values ('APV', 66);
insert into trenes (modelo, capacidad) values ('911', 67);
insert into trenes (modelo, capacidad) values ('Suburban 2500', 68);
insert into trenes (modelo, capacidad) values ('Monte Carlo', 69);
insert into trenes (modelo, capacidad) values ('Blazer', 70);
insert into trenes (modelo, capacidad) values ('RL', 71);
insert into trenes (modelo, capacidad) values ('Camry', 72);
insert into trenes (modelo, capacidad) values ('CTS', 73);
insert into trenes (modelo, capacidad) values ('RAV4', 74);
insert into trenes (modelo, capacidad) values ('Crown Victoria', 75);
insert into trenes (modelo, capacidad) values ('Sonoma Club Coupe', 76);
insert into trenes (modelo, capacidad) values ('Ram 1500 Club', 77);
insert into trenes (modelo, capacidad) values ('Solara', 78);
insert into trenes (modelo, capacidad) values ('A3', 79);
insert into trenes (modelo, capacidad) values ('9-2X', 80);
insert into trenes (modelo, capacidad) values ('HS', 81);
insert into trenes (modelo, capacidad) values ('F-Series', 82);
insert into trenes (modelo, capacidad) values ('Aveo', 83);
insert into trenes (modelo, capacidad) values ('Tahoe', 84);
insert into trenes (modelo, capacidad) values ('F350', 85);
insert into trenes (modelo, capacidad) values ('Camry Hybrid', 86);
insert into trenes (modelo, capacidad) values ('Econoline E150', 87);
insert into trenes (modelo, capacidad) values ('Z4', 88);
insert into trenes (modelo, capacidad) values ('Prius Plug-in Hybrid', 89);
insert into trenes (modelo, capacidad) values ('9000', 90);
insert into trenes (modelo, capacidad) values ('Titan', 91);
insert into trenes (modelo, capacidad) values ('4Runner', 92);
insert into trenes (modelo, capacidad) values ('S4', 93);
insert into trenes (modelo, capacidad) values ('Sentra', 94);
insert into trenes (modelo, capacidad) values ('Millenia', 95);
insert into trenes (modelo, capacidad) values ('Murano', 96);
insert into trenes (modelo, capacidad) values ('Aviator', 97);
insert into trenes (modelo, capacidad) values ('LaCrosse', 98);
insert into trenes (modelo, capacidad) values ('MKX', 99);
insert into trenes (modelo, capacidad) values ('A3', 100);
