insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Patricio Cherry Holme', 'Del Sol', '1984/01/26');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Brigit Herrema', 'Lyons', '1977/07/09');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Tammie Shermar', 'Wayridge', '1965/03/18');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Tarrance Evitts', 'Sunbrook', '1982/12/23');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Fidole Miettinen', 'Farragut', '1972/12/28');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Durward Polglase', 'Pine View', '1956/11/09');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Marybelle Peepall', 'Arrowood', '1999/09/08');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('James Works', 'Milwaukee', '1951/08/27');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Leonardo Harbron', 'Lake View', '1969/08/07');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Ernesta Gadson', 'Drewry', '1991/09/08');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Kittie Lowthorpe', 'Lakeland', '1981/02/20');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Druci Hartland', 'Granby', '1980/02/02');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Constantia Bladen', 'Susan', '1962/02/07');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Antonio Puzey', 'Dottie', '1981/02/18');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Mayne Simeone', 'Annamark', '1962/02/09');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Hayward Village', 'Saint Paul', '1975/02/14');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Elora Betteridge', 'Eagan', '1978/09/05');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Isa McGraw', 'Utah', '1967/08/28');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Janella Gyurko', 'Bonner', '1950/11/05');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Reynold Greenlies', 'Iowa', '1987/06/23');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Larisa Fishlee', 'Golf View', '1971/12/26');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Abner Burhill', 'Springview', '1970/07/30');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Asa Caine', 'American Ash', '1979/02/01');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Nathalia MacMearty', 'Summerview', '2002/10/15');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Ned McGunley', 'Welch', '1997/06/26');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Vladamir McGillacoell', 'Sugar', '1957/06/14');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Guillaume Marven', 'Melvin', '1975/12/03');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Natty McGeady', 'Evergreen', '1985/02/22');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Mario Chettoe', 'Susan', '1990/01/18');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Leonore Adamik', 'Comanche', '1986/12/19');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Joelie Sigart', 'Farragut', '1974/09/18');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Nadine Tamplin', 'Prentice', '1999/06/02');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Christean Stanett', 'Atwood', '1986/02/10');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Russell Tomblett', 'Sheridan', '1950/12/06');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Tiffie Welton', 'Reindahl', '1986/07/17');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Mikael Palphramand', 'Erie', '1989/09/13');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Felicle Otham', 'Huxley', '1991/02/03');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Ham Rutland', 'Thompson', '1963/07/25');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Alec Fredi', 'Alpine', '2000/04/06');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Katalin Oels', 'Dixon', '1998/11/20');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Kev Demogeot', 'Fairview', '1989/05/31');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Fifine Upham', 'Columbus', '2002/12/26');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Carlie Kyme', 'Corscot', '1951/12/18');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Marian Fysh', 'Eagan', '1950/08/30');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Ado Goby', 'Jay', '1957/04/27');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Belva Schule', 'Blue Bill Park', '1971/11/14');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Jacki Tapping', 'Bonner', '1975/03/29');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Jobyna Athelstan', 'Hoard', '1963/08/14');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Freemon Ovitz', 'Laurel', '1979/11/06');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Elroy Whardley', 'Transport', '1982/01/27');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Danika Statham', 'Troy', '1987/02/04');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Urson Lehenmann', 'Victoria', '1978/05/26');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Annabela O''Dreain', 'Magdeline', '1979/10/31');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Winslow Rawsen', 'Duke', '1962/07/27');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Rafaelita Hedgeman', 'Forest', '1976/12/06');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Melissa Phoebe', 'Mesta', '1969/06/14');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Fabiano Coppin', 'Brentwood', '1976/04/12');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Phyllida Leverette', 'Troy', '1984/07/20');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Raychel Trengrove', 'Butterfield', '1989/11/12');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Persis Corben', 'Knutson', '1959/07/02');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Reynold Kidgell', 'Sheridan', '1954/12/25');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Leilah Snelling', 'Golf Course', '2000/04/03');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Lanni Kench', 'Carey', '1988/06/07');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Heriberto Stacy', 'Commercial', '1953/03/18');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Margaretta Muddicliffe', 'Mariners Cove', '1977/11/23');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Linnell Rumney', 'Clarendon', '1958/11/24');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Bird Touhig', 'Novick', '1963/05/31');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Buddie de Bullion', 'Lake View', '1954/09/26');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Nevil Rampley', 'Crest Line', '1977/05/27');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Verine Keays', 'American', '2002/11/02');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Sylvia Whatford', 'Southridge', '1951/01/14');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Matty Simoneton', 'Sunnyside', '1957/10/28');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Delcine Seemmonds', 'Larry', '1979/12/26');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Malvina Danat', 'Golf View', '1962/08/11');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Golda McKeaveney', 'Susan', '1973/05/30');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Elianora Inston', 'Nobel', '1973/07/24');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Trixy Glacken', 'Artisan', '1969/12/23');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Timi Warrack', 'Mosinee', '1954/02/10');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Darice Pennock', 'Cody', '1972/04/02');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Gates Knobell', 'Brown', '1954/11/03');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Warden Debow', 'American Ash', '1966/03/31');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Idell Romagnosi', 'Blackbird', '1967/06/10');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Corie Baggarley', 'Waywood', '1973/06/08');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Kipper Shearsby', 'Pawling', '1985/09/17');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Keelia Lowell', 'Drewry', '1983/08/03');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Katlin Minter', 'Oxford', '1982/01/22');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Leanna Paliser', 'Longview', '1983/01/06');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Orsola Openshaw', 'Valley Edge', '1977/03/29');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Hazel Boodle', 'Marcy', '1990/11/11');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Genovera Martin', 'Forster', '1983/07/23');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Dalt Bickerstaffe', 'Lukken', '1957/08/18');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Maryjane Veazey', 'Johnson', '1979/05/21');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Daron Boots', 'Stuart', '1978/02/15');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Riordan De Gouy', 'Dixon', '1975/08/27');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Temple Dussy', 'Grasskamp', '1994/03/27');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Burt Oldroyde', 'Springview', '1992/03/02');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Latisha Grebbin', 'Bultman', '2000/05/01');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Pasquale Dayce', 'Sage', '1954/09/14');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Tanner Orrobin', 'Golden Leaf', '1952/11/23');
insert into pasajeros (nombre, direccion, fecha_nacimiento) values ('Marty Lunt', 'Golf View', '1976/04/08');
